config/routes.rb
Stores::Application.routes.draw do
  match "vendor/index"=>"vendor#index"
  match "user/index" => "user#index"
  match "customer/index" => "customer#index"
  match "customer/listing" => "customer#listing"
  match "customer/store_listing" => "customer#store_listing"
  match "customer/listing_items" => "customer#listing_items"
  match "customer/user_store_list" => "customer#user_store_list"
  match "customer/store_category_list" => "customer#store_category_list"
  match "customer/item_list" => "customer#item_list"
  match "customer/right_item_list" => "customer#right_item_list"
  match "customer/fav_list" => "customer#fav_list"
  match "customer/quantity" => "customer#quantity"
  match "customer/buy" => "customer#buy"
  match "customer/my_list" => "customer#my_list"
  match "customer/test_haml" => "customer#test_haml"
  match "customer/removed_list" => "customer#removed_list"

  match "home/index"=>"home#index"
  match "home/show_stores" => "home#show_stores"
  match "home/save_stores" => "home#save_stores"
  match "home/select_items" => "home#select_items"
  match "home/googlemaps" => "home#googlemaps"
  match "home/city" => "home#city"
  match "user/index" => "user#index"

  devise_for :users

   root :to => 'home#index'

end

app/models/store_category.rb
class StoreCategory < ActiveRecord::Base
   attr_accessible :store_id, :category_type_id, :category_name, :parent_id
   belongs_to :store
   has_many :items
   
  searchable do
    integer :id
=begin
integer :store_id
    integer :location_id do
      store.location_id
    end

    text :item_name do
      items.collect(&:item_name).compact if items.any?
    end
    text :price do
      items.collect(&:price).compact if items.any?
    end
    text :quantity do
      items.collect(&:quantity).compact if items.any?
    end
=end

  end
=begin
def self.category_level
     @category=
   end
=end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   layout 'home'

  def index
    @locations=Location.where('city_id',3493)
    @radius=(1..20)
#-------------------------------
@json=Store.all.to_gmaps4rails
#--------------------------------
   
  end

  def show_stores
    @location_id=params[:location_id]

  name=params[:item_name]
  locationid=params[:location_id]
  radius=params[:radius_id]
   @sets=Locationdistance.connection.select_all "select ids.location_id,ids.destination_id,ids.radius,s.id,s.store_name,i.item_name,i.price,i.id as item_id from
locationdistances ids join stores s on ids.destination_id=s.location_id
join store_categories cs on s.id=cs.store_id
join items i on i.store_category_id =cs.id
where ids.location_id=#{locationid} AND ids.radius <=#{radius} AND i.item_name like '%#{name}%'"
@storeids=[]
@sets.map{|i| @storeids << i['id']}
    @category=CategoryType.all

#      @store_id=params[:store_id]
#     unless params[:store_id].blank?
       @json=Store.find(@storeids)
#     else
#       @json=Store.all
#     end

#    stores=Store.search do
#    fulltext params[:item_name]
#    with(:location_id,params[:location_id])
#    end
#    @stores=stores.results
#
#    itemlist=Item.search do
#      fulltext params[:item_name]
#     # paginate(:page => params[:page], :per_page => 10)
#    end
#    @items=itemlist.results
#
#    @destlist=[]
#    locdist=Locationdistance.search do
#      with(:location_id,params[:location_id])
#      with(:radius,(1.0..params[:radius_id].to_f)) unless params[:radius_id].blank?
#     end
#    loc_distances=locdist.results
#    loc_distances.uniq{|x| @destlist << x.destination_id}
#
#    unless @items.blank?
#     @final_items_list,@final_stores_list,@arr_count = store_item_list_with_radius(@items,@location_id,@destlist)
#    end
#    logger.info"-------#{@final_items_list}--------"
   
  end

def save_stores
  params[:send_item][:item_ids].each do |c|
  logger.info "-----getme--#{c}-----"
  end
  
  render :js=>"alert('hi');" 
end

def select_items
end

def googlemaps
   @json=Store.find(params[:store_id])

end
  def city
    state_id=params[:state_id]
    @cities=City.where(:state_id=>state_id)
  end

end

app/helpers/home_helper.rb
module HomeHelper

  def store_item_list_with_radius(items,loc_id)
    final_stores_list=[]
    final_items_list=[]
    @items=items
    @location_id=loc_id
    @items.each do |i|
        store=Store.find(StoreCategory.find(i.store_category_id).store_id)
        location=Location.find(store.location_id)
        if location.id==@location_id.to_i
            @reqlocitem=i.id
            @reqlocstore=store.id
         end
        unless @destlist.blank?
             if @destlist.include?(location.id)
                final_stores_list <<  store.id
                final_items_list << i.id
             end
        else
           if @location_id==location.id
              final_stores_list << store.id
              final_items_list << i.id
           end
       end
    end

        unless @reqlocitem.blank?
          final_stores_list.insert(0,Store.find(@reqlocstore).id)
          final_items_list.insert(0,Item.find(@reqlocitem).id)
        end
      arr=(0..final_items_list.count.to_i-1)

    return final_stores_list,final_stores_list,arr
  end

end

app/views/home/_category_levels.html.erb
<script>
    $(document).ready(function()
    {
        $("#coursecat > li > a").not(":first").find("+ ul").slideUp(1);
        $("#coursecat > li > a").click(function()
        {
            $(this).find("+ ul").slideToggle("fast");

        });
    });

</script>

<style>
    #coursecat li {
        list-style: none;
    }

    #coursecat, #coursecat ul {
        list-style: none outside none;
        padding: 3px;
    }
    #coursecat, #coursecat ul {
        list-style: none;
    }
    #coursecat a {
        color: #010101;
        display: block;
        font-weight: bold;
        padding: 0.5em 1em;
        text-decoration: none;
        text-align: left;
    }
    #coursecat ul a {
        color: #666;
        font-weight: normal;
        text-decoration: none;
        text-align: left !important;
    }

    #coursecat ul a:hover {
        text-decoration: underline;
        border-color: #BBBBBB;
        color: #711515;
        background-image: -moz-linear-gradient(center top, #ffffff , #ECECEC );
    }
    table#listing .tr-even td {
        color: #678197;
        font-size: 13px;
        font-weight: normal;
        padding: 0.5em 0.5em !important;
        text-align: center;
    }
</style>

<div id="locations_with_radius">

</div>
<!-- =============================================qmr edit================== -->

<div style="width:400px;">
  <% store_array = []%>
  <% @store=Store.all%>
  <%  @category_types=CategoryType.all%>
  <% @store.map{|i| store_array << i.id}%>
  <!-- ====================== -->
  <% logger.info"________________#{store_array}"%>

  <ul id="coursecat">
    <% unless @category_types.nil?%>
        <% @category_types.each do |list|%>
            <li>
              <a xxx=""><%= list.name%></a>

              <% @categry=Category.where("category_type_id='#{list.id}' AND parent_id IS NULL ")%>


              <ul id="coursecat">
                <%@categry.each do |list1|%>
                    <li>
                      <a xxx=""><%= list1.category_name%></a>
                      <% @sublvl=Category.where("parent_id='#{list1.id}'")%>
                      <ul id="coursecat">
                        <%@sublvl.each do |sub_lvl|%>
                            <li>
                              kk<%= sub_lvl.category_name%>
                            </li>
                        <%end%>
                      </ul>
                    </li>
                <%end%>
              </ul>

            </li>
        <%end%>
    <%end%>
  </ul>
  <!-- ========================== -->

</div>

</span>

app/views/home/_city.html.erb
        kkkkkkkkkkkkkkkkkkkkkkkkk
         <%= params[:state_id]%>
    <%#= f.select :city_id, options_for_select(@cities.collect{|u| [u.city_name,u.city_id]}),:prompt=>'select city',:locals => {:form => f, :field_type => 'email_field'}%>

app/views/home/_country.html.erb
<%@country=Country.find(101)%><%@states=@country.states%><%#@cities=@country.cities%>
<%= f.select :state_id, options_for_select(@states.collect{|u| [u.state_name,u.state_id]}),{},:onChange=>"$.ajax({url: '../home/city',data: 'state_id=' + value});"%>
<div id="city_par"> <%= f.select :city_id, options_for_select(@cities.collect{|u| [u.city_name,u.city_id]}),:prompt=>'select city'%></div>

app/views/home/_items_list.html.erb
<style>
  .show-grid [class*="span"] {
    background-color: #EEEEEE;
    border-radius: 3px 3px 3px 3px;
    line-height: 20px;
    min-height: 0px;height:32px;
    font-size:13px;
    text-align: center;
    margin:3px 0 0 0;
}
h1, h2, h3, h4, h5, h6 {margin:4px 0;}
.row-fluid .span1 { width: 6.983%;border:1px solid #DFDFDF;min-height:0px;height:25px;}
.row-fluid .span4{width: 21.624%;border:1px solid #DFDFDF;min-height:0px;height:25px;}
.row-fluid .span6{ width: 33.718%;border:1px solid #DFDFDF;min-height:0px;height:25px;}
</style>

<%unless @sets.blank?%>

<div class="row-fluid show-grid">
  <%=form_tag home_select_items_path,:remote=>true do%>
  <div id="item_list" class="span12">
    <div class="span1"><h6></h6></div><div class="span6"><h6>Item</h6></div><div class="span4"><h6>Store</h6></div>
    <div class="span4"><h6>Location</h6></div><div class="span1"><h6>Radius</h6></div>
    <div class="span1"><h6>Price</h6></div>
  </div>

 <%@sets.each do |i|%>
    <div id="item_list" class="span12">
    <div class="span1"><%=check_box_tag 'item_check',i['item_id'].to_i, false,:onchange=>"$.ajax({url: '../home/sub_category',data: 'category=' + value})"%></div>
    <div class="span6"><%=i['item_name']%></div>
    <div class="span4"><%=i['store_name']%></div>
    <div class="span4"><%=Location.find(i['destination_id']).location_name%></div>
    <div class="span1"><%=i['radius']%></div>
    <div class="span1"><%=i['price']%></div>
    </div>
<%end%>
<%end%>
</div>

<%else%>
No Items Found
<%end%>


         

app/views/home/_show_stores.html.erb
<style>
  #chk{width:10px;}
  #stor{width:20%;}
  #loc{width:20%;}
  #price{width:20%;}
</style>

<%= select_tag "category_id", options_from_collection_for_select(@category, "id", "name"),:prompt=>'select Categories'%><%#  :onchange=>"$.ajax({url: '../home/sub_category',data: 'category=' + value})"%>

<%unless @sets.blank?%>

<span id="chk"></span><span id="stor">Store</span><span id="loc">Location</span>
  <%=form_tag home_save_stores_path,:remote=>true do%>

          <%@sets.each do |i|%>
           <span id="chk"><%= check_box_tag "send_item[item_ids][]",i['item_id'].to_i, false , :onclick=>"$.ajax({url: '../home/googlemaps',data: 'store_id=' + #{i['id']}})"%></span>
           <span id="stor"><%=i['store_name']%></span>
           <span id="loc"><%=Location.find(i['destination_id']).location_name%></span><br/>
          <%end%>
  <%end%>


<%else%>
No Items Found
<%end%>

app/views/home/city.js.erb
$("#city_par").html('<%= escape_javascript(render "city")%>');

app/views/home/googlemaps.js.erb
$('#map_section').html('<%= escape_javascript( gmaps({:last_map => false}) ) %>');

Gmaps.map = new Gmaps4RailsGoogle();
Gmaps.load_map = function() {
    Gmaps.map.map_options.maxZoom = 15;
    Gmaps.map.initialize();
    Gmaps.map.markers = <%=raw @json.to_gmaps4rails %>;
    Gmaps.map.create_markers();
    Gmaps.map.adjustMapToBounds();
    Gmaps.map.callback();
};
Gmaps.loadMaps();

app/views/home/index.html.erb
<style type="text/css">
  .hero-unit{
    padding: 174px 174px 174px 280px;
   /* background-image: linear-gradient(to bottom, #FFFFA0, #FF9F3E); */
}
.span9{margin-left: 174px;margin-top:50px;}
</style>

         
<div id="main_list" style="height:250px;overflow:auto;">
  
  </div>

  <div id="map_section">
    <%= gmaps4rails(@json) %>
  </div>

app/views/home/show_stores.js.erb
$('#list_left').html('<%=escape_javascript(render 'show_stores')%>');
$('#main_list').html('<%=escape_javascript(render 'items_list')%>');

$('#map_section').html('<%= escape_javascript( gmaps({:last_map => false}) ) %>');

Gmaps.map = new Gmaps4RailsGoogle();
Gmaps.load_map = function() {
    Gmaps.map.map_options.maxZoom = 15;
    Gmaps.map.initialize();
    Gmaps.map.markers = <%=raw @json.to_gmaps4rails %>;
    Gmaps.map.create_markers();
    Gmaps.map.adjustMapToBounds();
    Gmaps.map.callback();
};
Gmaps.loadMaps();