config/routes.rb
Stores::Application.routes.draw do
  match "vendor/index"=>"vendor#index"
  match "user/index" => "user#index"
  match "customer/index" => "customer#index"
  match "customer/listing" => "customer#listing"
  match "customer/store_listing" => "customer#store_listing"
  match "customer/listing_items" => "customer#listing_items"
  match "customer/user_store_list" => "customer#user_store_list"
  match "customer/store_category_list" => "customer#store_category_list"
  match "customer/item_list" => "customer#item_list"
  match "customer/right_item_list" => "customer#right_item_list"
  match "customer/fav_list" => "customer#fav_list"
  match "customer/quantity" => "customer#quantity"
  match "customer/buy" => "customer#buy"
  match "customer/my_list" => "customer#my_list"
  match "customer/test_haml" => "customer#test_haml"
  match "customer/removed_list" => "customer#removed_list"

  match "home/index"=>"home#index"
  match "home/show_stores" => "home#show_stores"
  match "home/save_stores" => "home#save_stores"
  match "home/select_items" => "home#select_items"
  match "home/googlemaps" => "home#googlemaps"
  match "home/city" => "home#city"
  match "user/index" => "user#index"

  devise_for :users

   root :to => 'home#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :address, :city_id, :email, :first_name, :last_name, :location_id,:userid

end

app/models/store_category.rb
class StoreCategory < ActiveRecord::Base
   attr_accessible :store_id, :category_type_id, :category_name, :parent_id
   belongs_to :store
   has_many :items
   
  searchable do
    integer :id
=begin
integer :store_id
    integer :location_id do
      store.location_id
    end

    text :item_name do
      items.collect(&:item_name).compact if items.any?
    end
    text :price do
      items.collect(&:price).compact if items.any?
    end
    text :quantity do
      items.collect(&:quantity).compact if items.any?
    end
=end

  end
=begin
def self.category_level
     @category=
   end
=end
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  layout 'customer_dashboard'

  def index
    @radius=Locationdistance.select(:radius).order('radius ASC').uniq

    if request.post?
      @search=Location.search do
        fulltext "#{params[:location_name]}"
      end
      @location_list=@search.results
      logger.info "--------------#{@location_list}"
    end
  end

  def store_listing
    @radius=Locationdistance.select(:radius).order('radius ASC').uniq

    @search=Locationdistance.search do
      fulltext params[:location_name]
      with(:radius,(1.0..params[:radius].to_f)) unless params[:radius].blank?
    end
    location_list=@search.results
    mainlist=[]
    destlist=[]
    location_list.uniq{|x| mainlist << x.location_id}
    location_list.uniq{|x| destlist << x.destination_id}
    @listelements=(mainlist.uniq+destlist.uniq).uniq

  end

  def listing_items
    @store=Store.find(params[:store_id])
    #@storeitems=Storeitem.where("store_id",@store.id).page(params[:page]).per(10)
    @search=Storeitem.search do
      with(:store_id,params[:store_id])
      paginate(:page => params[:page], :per_page => 12)
    end
    @storeitems=@search.results
    #-----------------

    #    items=Item.all
    #    items.each do |i|
    #      vend=Category.find(i.category_id).vendor_id
    #      stores=Store.where("vendor_id = ?",vend)
    #      logger.info"-----icame1---------"
    #      stores.each do |s|
    #        logger.info"-----icame2---------"
    #        Storeitem.create(:store_id=>s.id,:item_id=>i.id,:quantity=>10)
    #        logger.info"-----icame3---------"
    #      end
    #    end
    #-----------------
  end
  def listing

  end
  def user_store_list
    @store_value=params[:store_id]
    @user_id=current_user.id
    #CustomerStore.where("store_id and customer_id",@store_value)
    if @store_value
      @check_store_list=CustomerStore.find_by_sql("select id  from customer_stores where store_id=#{@store_value} and customer_id=#{@user_id}")
      if @check_store_list.blank?
        @user_store_save= CustomerStore.new(:store_id=>@store_value,:customer_id=>current_user.id)
        if @user_store_save.save
          #render :js=> '$("#message").html("Added to Store list");'
          #render :js=>"$('#cart').append(#{@test});"
          @message="Added to Store list"
        end
      else
        @message="Already Store has been added to Store List"
        #render :js=> '$("#message").html("Already Store has been added to Store List");'
      end
    end
  end
  def store_category_list
    @store_id=params[:store_id]

    if   @store_id
      #@store_category_type=StoreCategory.find_by_sql("select distinct category_type_id from store_categories where store_id=#{@store_id}")
      @store_category_type=StoreCategory.connection.select_all"SELECT DISTINCT sc.category_type_id, sc.store_id,ct.name
        FROM store_categories sc
        JOIN category_types ct ON sc.category_type_id = ct.id WHERE sc.store_id =#{@store_id}"
      #logger.info"#{ params[:item_arry]}"
      @a=params[:item_arry]
    end
  end
  def item_list
    if params[:store_id] and params[:store_cat_id]
      @store_item=Item.where("store_category_id=#{params[:store_cat_id]}").select("id,price,item_name")
    end
  end
  #@@cc=Array.new
  def right_item_list
      #@cc=Array.new
    #logger.info"#{ params[:item_arry]}"

       @a=params[:item_arry].split(",")
  end
    def fav_list

      logger.info"hjjjjjjjjjjjjjjjjjfgsdf#{params[:item_ids].class}"

        @search=params[:item_ids]
=begin
if params[:item_id]
        @search=params[:selected_arry].split(",")

       #@search.delete(params[:item_id])
      else
        @search=params[:selected_arry].split(",")
      end

=end
      if params[:add_list].to_i==1
        logger.info"enter fave listtttttttttttttttttttttttttttt"
        Item.item_details(@search,"#{params[:list_name]}",current_user.id)
      end
    end
  def quantity
=begin
@quan=params[:quantity].to_i
    @pro_price=params[:price].to_i
    @total=@quan * @pro_price

    logger.info"------------#{@quan}--#{@pro_price}------"
    flash[:notice] = "Product was successfully created."
    render :js=>"$('#quantitys#{params[:item_id]}').html(#{@total});"
=end
    @remove_item_id=params[:item_id]
    logger.info"------------#{@remove_item_id.class}--#{params[:all_items]}------"
    @list=params[:all_items]
    @list.delete(@remove_item_id)
    logger.info"classsssssssssssss#{@list}"

  end
  def buy
    if params[:pay_at_store]
      logger.info"sdsdsdsdsdd#{params[:quantity267]}"
      logger.info"twooooooooooo   Pay at Store"
    elsif params[:pay_online]
      logger.info"sdsdsdsdsdd#{params[:quantity267]}"
      logger.info"twooooooooooo   Pay Online"
    end

  end
  def my_list
   @my_list=CustomerItem.where("customer_list_id = ?",params[:cust_list_id])
  end
  def test_haml
       logger.info"sdsdsdsdsdd#{params[:accept2]}"

  end
    def removed_list

    end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customer/_bread_crumb.html.erb
<style>
.dropdown-menu {
    background-clip: padding-box;
    background-color: #FFFFFF;
    border: 1px solid rgba(0, 0, 0, 0.2);
    border-radius: 6px 6px 6px 6px;
    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
    display: block;
    float: left;
    left: 0;
    list-style: none outside none;
    margin: 2px 0 0 500px;
    min-width: 160px;
    padding: 5px 0;
    position: absolute;
    top: 100%;
    z-index: 1000;
}

.dropdown-submenu > .dropdown-menu {
    border-radius: 0 6px 6px 6px;
    left: 100%;
    margin-left: -1px;
    margin-top: -6px;
    top: 0;
    display:none;
}
</style> 

<li><a href="#"><%=Location.find(params[:location_id]).location_name%> </a> <span class="divider">/</span></li>
 <li><a href="#"><%=@store.store_name%></a> <span class="divider">/</span></li>
    <li class="active">Data</li>

 <div class="dropdown clearfix">
                <ul aria-labelledby="dropdownMenu" role="menu" class="dropdown-menu">
                 <li class="dropdown-submenu">
                    <a href="#" tabindex="-1">More options</a>
                    <ul class="dropdown-menu">
                      <li><a href="#" tabindex="-1">Second level link</a></li>
                      <li><a href="#" tabindex="-1">Second level link</a></li>
                    </ul>
                  </li>
                  <li class="dropdown-submenu">
                    <a href="#" tabindex="-1">third options</a>
                    <ul class="dropdown-menu">
                      <li><a href="#" tabindex="-1">third level link</a></li>
                      <li><a href="#" tabindex="-1">third level link</a></li>
                    </ul>
                  </li>
                </ul>
              </div>

app/views/customer/_checked_list.erb
<%=@a%>

app/views/customer/_fav_list_removed.erb
<% @tot=0%>
<!--<table>

  <tr><td>select</td><td>Item</td><td>Item Price</td><td>Quantity</td><td>total Price</td></tr>-->
<%=form_tag customer_buy_path do %>
    <%@search.each do |i|  %>
        <%@it=Item.find(i.to_i)%>

        <div id="list<%=i%>">

          <tr>
            <td><%#=check_box_tag "items#{i}","#{i}",false,:onclick=>"removeFormList()"%>
              <%= link_to "Remove","#",:onclick=>"removeFormList(#{i},#{@search})" %>
            </td>
            <td> <%=@it.item_name%></td>
            <td> <%=@it.price%>  </td>
            <%#%>  <% @tot=@it.price+@tot%>
            <%@quantity= [1,2,3,4,5,6]%>
            <td>   <%#=select_tag "quantity#{i}",options_for_select(@quantity.collect{|u| u}),:onchange=>"$.ajax({url: '../customer/quantity',data: 'quantity=' + value + '&price=' + #{@it.price} + '&item_id=' + #{i} })"%>
              <%=select_tag "quantity#{i}",options_for_select(@quantity.collect{|u| u}),:onchange=>"quantity_total(this.value,#{@it.price},#{i},#{@search})"%>
            </td>
            <div id="quantitys<%=i%>"><%=@it.price%></div>  </tr>
        </div>
    <%end%>
    <tr> <td><%= submit_tag "Pay at Store",:name=>"pay_at_store" %></td>
      <td><%= submit_tag "Pay Online",:name=>"pay_online" %></td>
    </tr>

<%end%>
</table>
<div id="total_value"><%=@tot%></div>

app/views/customer/_listing.html.erb
<style>
  .row-fluid .span4 {
    width: 18.624%;
}
 h5{font-size:12px;}
 p{font-size:10px; }
.row-fluid [class*="span"]:first-child {
    margin-left: 1.8%;
}
.row-fluid .span10 {
    height: auto;
    width: 64%;
}
.thumbnail:hover{border-color:#0088CC}
</style>

<div class="row-fluid">
     
      <%=paginate @storeitems,:remote => true %>

      <ul class="thumbnails">
            <%@storeitems.each do |store|%>
              <li class="span4">
                <div class="thumbnail">
                  <%= image_tag('itemicon.jpg',:border=>"none")%>
                  <div class="caption">
                    <%unless store.item_id.blank?%>
                    <%item=Item.find(store.item_id)%>
                    <h5><%= truncate(item.item_name,:length=>20)%></h5>
                    <p>This item is from <%=Category.find(item.category_id).category_name unless item.category_id.blank?%> category</p>
                    <%else%>
                    <h3>Wrong Item</h3>
                    <p>No Category</p>
                    <%end%>
               <!--     <p><a href="#" class="btn btn-primary">Action</a> <a href="#" class="btn">Action</a></p>  -->
                  </div>
                </div>
              </li>
              <%end%>
           </ul>
   <%=paginate @storeitems,:remote => true %>
</div>

<%#------------------------------------my----------------------------------%>

app/views/customer/_menu_list.html.erb
<!--
<script type="text/javascript">
    /*function store_category()
     {
     $("#category_menu").html("<%#= escape_javascript (render 'customer/user_stores')%>")
     }*/
    $(document).ready(function(){
        $("#store_menu").click(function(){
            $("#category_menu").toggle();
            $("#category_menu").html("<%#= escape_javascript (render 'customer/user_stores')%>")
        });
    });
</script>

<style>
    #menu_list li {
        list-style: none;
    }
</style>
<ul id="menu_list">
  <li>My List</li>
  <li>
    <%#@store_list=CustomerStore.count_store_list(current_user)%>
<%#if @store_list.blank?%>
        My Store List(0)
    <%#else%>
        <div id="store_menu">  My Store List(<%#= @store_list.count %>) </div>

        <div id="category_menu"></div>
    <%#end%>
  </li>
  <li>My Purshared List</li>
  <li>My Recent Ordered List</li>
</ul>
========================Code Change-------------------  -->


<script>
    $(document).ready(function()
    {
        $("#menulist > li > a").not(":first").find("+ ul").slideUp(1);
        $("#menulist > li > a").click(function()
        {
            $(this).find("+ ul").slideToggle("fast");

        });
    });

</script>

<style>
    #menulist li {
        list-style: none;
    }

    #menulist, #menulist ul {
        list-style: none outside none;
        padding: 3px;
    }
    #menulist, #menulist ul {
        list-style: none;
    }
    #menulist a {
        color: #010101;
        display: block;
        font-weight: bold;
        padding: 0.5em 1em;
        text-decoration: none;
        text-align: left;
    }
    #menulist ul a {
        color: #666;
        font-weight: normal;
        text-decoration: none;
        text-align: left !important;
    }

    #menulist ul a:hover {
        text-decoration: underline;
        border-color: #BBBBBB;
        color: #711515;
        background-image: -moz-linear-gradient(center top, #ffffff , #ECECEC );
    }
    table#listing .tr-even td {
        color: #678197;
        font-size: 13px;
        font-weight: normal;
        padding: 0.5em 0.5em !important;
        text-align: center;
    }
</style>


<div id="locations_with_radius">

</div>
<!-- =============================================qmr edit================== -->
<span>
<div style="width:400px;">

  <ul id="menulist">

    <li>
      <a xxx="">My List </a>
      <%list=CustomerList.where("customer_id = ?",current_user.id)%>
      <ul id="menulist">
        <%unless list.blank?%>
            <%list.each do |lname|%>
                <li>
                        <%=link_to "#{lname.list_name}" ,customer_my_list_path(:cust_list_id=>"#{lname.id}"),:remote =>true %>
                </li>
            <%end%>
        <%end%>
      </ul>

    </li>
    <li>
      <%@store_list=CustomerStore.count_store_list(current_user)%>
      <%unless @store_list.blank?%>
          <a xxx=""> My Store List(<%= @store_list.count %>)  </a>

          <ul id="menulist">
            <%@store_list.each do |i|%>

                <li>
                  <%=link_to "#{Store.find(i.store_id).store_name}" ,"#",:onclick=>"view_category_list(#{i.store_id})" %>
                </li>

            <%end%>
          </ul>
      <%else%>
          <a xxx=""> My Store List(0) </a>
      <%end%>


    </li>
    <li>
      <a xxx="">My Purshared List </a>
      <ul id="menulist">

        <li>
          <a xxx="">1</a>

          <ul id="menulist">

            <li>
              2
            </li>

          </ul>
        </li>

      </ul>

    </li>
    <li>
      <a xxx="">My Recent Ordered List</a>
      <ul id="menulist">

        <li>
          <a xxx="">1</a>

          <ul id="menulist">

            <li>
              2
            </li>

          </ul>
        </li>

      </ul>

    </li>

  </ul>
  <!-- ========================== -->

</div>

</span>

app/views/customer/_mylist.html.erb
<!--<table border="1">
  <tr><td>select</td><td>Item</td><td>Item Price</td><td>Quantity</td><td>total Price</td></tr>-->
  <%=form_tag customer_buy_path do %>
      <%@my_list.each do |j|  %>
          <%@it=Item.find(j)%>

          <%=check_box_tag "items#{@it.id}","#{@it.id}"%>
          <%=@it.item_name%>
          <%=@it.price%>
          <%@quantity= [1,2,3,4,5,6]%>
          <%=select_tag "quantity#{@it.id}",options_for_select(@quantity.collect{|u| u}),:onchange=>"$.ajax({url: '../customer/quantity',data: 'quantity=' + value + '&price=' + #{@it.price} + '&item_id=' + #{@it.id} })"%>
          <%#=select_tag "quantity",options_for_select(@quantity.collect{|u| u}),:onchange=>"alert('swathi')"%>

          <div id="quantitys<%=@it.id%>"> </div>
          <br/>

      <%end%>
      <%=submit_tag "Pay"%>
  <%end%>
  <!--</table>-->
<%#=@my_list.inspect%>

app/views/customer/_store_item_list.html.erb
<script>

    $(document).ready(function(){
       for (var i=0;i<allVals.length;i++)
       {
             var a= '#' + allVals[i];
            $(a).prop('checked', true);
        }

    });

</script>

<div id="cab">
      <%@store_item.each do |item|%>
          <%= check_box_tag  "#{item.id}","#{item.id}",false,:onChange=>"updateTextArea()" %> <%=item.id%>
          <%#= check_box_tag 'item_ids[]',"#{item.id}",:onclick=>"$.ajax({url: '../customer/right_item_list',data: 'item_arry=' + value });" -%>
          <%= item.item_name -%>

      <%end%>

</div>
   <div id="all">
     </div>
<%#@category=Category.all%>
<%#= select_tag "category_id", options_for_select(@category.collect{|u| [u.category_name,u.id] }),:prompt=>'select Categories',:onchange=>"$.ajax({url: '../customer/right_item_list',data: 'item_arry=' + value });"%>
<!--http://stackoverflow.com/questions/786142/how-to-retrieve-checkboxes-values-in-jquery-->

app/views/customer/item_list.js.erb
$('#item_list').html('<%= escape_javascript(render "store_item_list")%>');

app/views/customer/listing.html.erb
<!--no store in ganianagar-->

<div id="user_location">
  <% @location=Location.user_location(current_user) %>
  <%=@location[0].location_name%><%= current_user.location_id%>
</div>
<div class="alert"></div>
<div id="get_stores_user">

  <%= render 'customer/locationwise_user_stores_list'%>

</div>

<div id="item_list">


</div>
<div id="select_item_list">


</div>
<div id="my_list">


</div>

app/views/customer/removed_list.js.erb
$("#remove_list").html("<%= escape_javascript(render 'fav_list_removed')%>");

app/views/customer/right_item_list.js.erb
$("#items").html('<%= escape_javascript (render 'user_stores')%>');

app/views/customer/store_category_list.js.erb
$('#store_category').html('<%=escape_javascript (render 'store_category_levels') %>')

app/views/customer/store_listing.js.erb
$("#locations_with_radius").html('<%= escape_javascript(render "locations_radius_list")%>'); 

app/views/customer/user_store_list.js.erb
$("#hello").html('<%= escape_javascript (render 'customer/menu_list' )%>');
$(".alert").html('<%= @message %>');
$("#get_stores_user").html('<%= escape_javascript (render 'customer/locationwise_user_stores_list' )%>');