config/routes.rb
Stores::Application.routes.draw do
  match "vendor/index"=>"vendor#index"
  match "user/index" => "user#index"
  match "customer/index" => "customer#index"
  match "customer/listing" => "customer#listing"
  match "customer/store_listing" => "customer#store_listing"
  match "customer/listing_items" => "customer#listing_items"
  match "customer/user_store_list" => "customer#user_store_list"
  match "customer/store_category_list" => "customer#store_category_list"
  match "customer/item_list" => "customer#item_list"
  match "customer/right_item_list" => "customer#right_item_list"
  match "customer/fav_list" => "customer#fav_list"
  match "customer/quantity" => "customer#quantity"
  match "customer/buy" => "customer#buy"
  match "customer/my_list" => "customer#my_list"
  match "customer/test_haml" => "customer#test_haml"
  match "customer/removed_list" => "customer#removed_list"

  match "home/index"=>"home#index"
  match "home/show_stores" => "home#show_stores"
  match "home/save_stores" => "home#save_stores"
  match "home/select_items" => "home#select_items"
  match "home/googlemaps" => "home#googlemaps"
  match "home/city" => "home#city"
  match "user/index" => "user#index"

  devise_for :users

   root :to => 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :category_name, :category_type_id, :parent_id
end

app/models/category_type.rb
class CategoryType < ActiveRecord::Base
  attr_accessible :name
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :city_name, :state_id
  belongs_to :state
  has_many :locations
end

app/models/country.rb
class Country < ActiveRecord::Base
 attr_accessible :country_call_code, :country_code, :country_name
 has_many :states
 has_many :cities, :through => :states
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :address, :city_id, :email, :first_name, :last_name, :location_id,:userid

end

app/models/customer_item.rb
class CustomerItem < ActiveRecord::Base
  attr_accessible :customer_list_id, :item_id
end

app/models/customer_list.rb
class CustomerList < ActiveRecord::Base
  attr_accessible :customer_id, :customer_store_id, :list_name

end

app/models/customer_order.rb
class CustomerOrder < ActiveRecord::Base
  attr_accessible :order_number, :payment_approved, :payment_completed, :payment_type, :total_price
end

app/models/customer_store.rb
class CustomerStore < ActiveRecord::Base
  attr_accessible :customer_id, :store_id
  scope :count_store_list , lambda { |user|
    where("customer_id = ?", user.id)
    #find(user.location_id)
  }
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :store_category_id, :item_description, :item_name, :price, :quantity
  has_many :storeitems
  belongs_to :store_category
  
   searchable do
    text :item_name
    text :item_description
    integer :price
#    integer :location_id do
#      store.location_id
#    end
#    double :store_id , :multiple => true , :references => Storeitem do
#      storeitems.collect(&:store_id).compact if storeitems.any?
#    end
   end
  def self.item_details(item_ids,list_name,customer_id)
    logger.info"--------------#{item_ids}-------------------"
    store_cat=Item.where("id = ?",item_ids.first.to_i).select("store_category_id").first
   store=StoreCategory.where("id = ?",store_cat.store_category_id).select("store_id").first
    #puts "#{store.store_id}-------------------store"
    #puts "#{store_cat.store_category_id}---------------cat"
    #.m.m,.m,.m,.
   list=CustomerList.create(:customer_id=>customer_id,:customer_store_id=>store.store_id,:list_name=>list_name)
    item_ids.each do |i|
      s=CustomerItem.new(:item_id=>i.to_i,:customer_list_id=>list.id)
      s.save
    end
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :location_name, :city_id
  has_many :locationdistances
  has_many :stores
  belongs_to :city

  searchable do
  text :location_name
  integer :id
#  integer :location_id do
#    locationdistances.location_id if locationdistances=self.locationdistances
#  end
#  double :radius do
#    locationradius.radius if locationradius = self.locationradius
#   end

   double :radius , :multiple => true , :references => Locationdistance do
      locationdistances.collect(&:radius).compact if locationdistances.any?
   end
  end

  scope :user_location, lambda { |user|
    where("id = ?", user.location_id)
    #find(user.location_id)
  }
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :role_name
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :country_id, :state_name
  belongs_to :country
  has_many :cities
end

app/models/store.rb
class Store < ActiveRecord::Base
  attr_accessible :city_id, :location_id, :store_address, :store_name, :vendor_id, :longitude ,:latitude
  belongs_to :location
  #has_many :stores ,:through => :locations
  has_many :store_categories
  #has_many :items , :through=>:store_categories
  acts_as_gmappable
  def gmaps4rails_address
#describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    store_address
  end
  def gmaps4rails_infowindow
    store_address
  end

  searchable do
    integer :location_id
    text :location_name do
      location.location_name
    end
    text :item_name do
      items.collect(&:item_name).compact if items.any?
    end
  end




end

app/models/store_category.rb
class StoreCategory < ActiveRecord::Base
   attr_accessible :store_id, :category_type_id, :category_name, :parent_id
   belongs_to :store
   has_many :items
   
  searchable do
    integer :id
=begin
integer :store_id
    integer :location_id do
      store.location_id
    end

    text :item_name do
      items.collect(&:item_name).compact if items.any?
    end
    text :price do
      items.collect(&:price).compact if items.any?
    end
    text :quantity do
      items.collect(&:quantity).compact if items.any?
    end
=end

  end
=begin
def self.category_level
     @category=
   end
=end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:role_id,:state_id, :city_id, :location_id, :address, :street
  # attr_accessible :title, :body

   def add_user_role
    create_customer if self.customer?
    create_vendor if self.vendor?
   end

   def role_name
    return 'admin' if self.role_id==1
    return 'customer' if self.role_id==2
    return 'vendor' if self.role_id==3
   end

   def admin?
    return self.role_id==1 ? true : false
   end

   def customer?
    return self.role_id==2 ? true : false
   end

   def vendor?
    return self.role_id==3 ? true : false
   end

  def create_customer
    Customer.create(:email=>self.email,:userid=>self.id)
  end

  def create_vendor
    Vendor.create(:userid=>self.id)
  end

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  attr_accessible :contact, :description, :vendor_name,:userid
end

app/helpers/home_helper.rb
module HomeHelper

  def store_item_list_with_radius(items,loc_id)
    final_stores_list=[]
    final_items_list=[]
    @items=items
    @location_id=loc_id
    @items.each do |i|
        store=Store.find(StoreCategory.find(i.store_category_id).store_id)
        location=Location.find(store.location_id)
        if location.id==@location_id.to_i
            @reqlocitem=i.id
            @reqlocstore=store.id
         end
        unless @destlist.blank?
             if @destlist.include?(location.id)
                final_stores_list <<  store.id
                final_items_list << i.id
             end
        else
           if @location_id==location.id
              final_stores_list << store.id
              final_items_list << i.id
           end
       end
    end

        unless @reqlocitem.blank?
          final_stores_list.insert(0,Store.find(@reqlocstore).id)
          final_items_list.insert(0,Item.find(@reqlocitem).id)
        end
      arr=(0..final_items_list.count.to_i-1)

    return final_stores_list,final_stores_list,arr
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/vendor_helper.rb
module VendorHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    .brand b{font-size:35px;}
    .navbar .nav {float: right;}
  </style>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="<%=root_url%>"><b>Aloo.com</b></a>
        <div class="nav-collapse">
          <ul class="nav">
            <% if user_signed_in? %>
            <li><a href=""> Logged in as <%= current_user.email %></a></li>
               <%if current_user.customer?%>
            <li><%=link_to 'My Dashboard',customer_listing_path%></li>
               <%elsif current_user.vendor?%>
            <li><%=link_to 'My Dashboard',vendor_index_path%></li>
               <%end%>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, :method=>:delete %></li>
            <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>

            <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">

      <div class="span9"><%= yield %></div>
     
    </div>
  </div>
</body>
</html>

app/views/layouts/customer_dashboard.html.erb
<head>
  <title>Store</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
   .row-fluid .span2{background:#BBD8E9;height:90%;}
   .row-fluid .span10{background:#FAFAFA;height:auto;width:65%; }
   
  </style>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="<%=root_url%>"><b>Aloo.com</b></a>
        <div class="nav-collapse">
          <ul class="nav">
            <% if user_signed_in? %>
            <li><a href=""> Logged in as <%= current_user.email %></a></li>
               <%if current_user.customer?%>
            <li><%=link_to 'My Dashboard',customer_listing_path%></li>
               <%elsif current_user.vendor?%>
            <li><%=link_to 'My Dashboard',vendor_index_path%></li>
               <%end%>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, :method=>:delete %></li>
            <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
               nmbnmbnmb
                <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  
<div class="container-fluid">
    <div class="row-fluid">
    	
    <div class="span2">
   <div class="block1">
   	<div class="title">Menu
                 <div id="hello">
                   <%= render 'customer/menu_list' %>
                 </div>


       </div>
   	
   	
   </div>
   <div class="block2">
   		<div class="title">Near By Stores[category list]
             <div id="store_category">

             </div>
          </div>
   	
   </div>
    </div>
    <div class="span10">
    <ul class="breadcrumb">
   
    </ul>
    <%= yield %>
    </div>
   
    <div class="span2">
    	<div class="right_bar">
    		<div class="title">
    			Search
              <div id="items"> </div>
    		</div>
    	</div>
   
    </div>
    </div>
    </div>
</body>

app/views/layouts/home.html.erb
<!--<VirtualHost *:80>
ServerName www.yourhost.com
# !!! Be sure to point DocumentRoot to 'public'!
DocumentRoot /somewhere/public
<Directory /somewhere/public>
# This relaxes Apache security settings.
AllowOverride all
# MultiViews must be turned off.
Options -MultiViews
</Directory>
</VirtualHost>
LoadModule passenger_module /usr/lib/ruby/gems/1.8/gems/passenger-3.0.19/ext/apache2/mod_passenger.so
PassengerRoot /usr/lib/ruby/gems/1.8/gems/passenger-3.0.19
PassengerRuby /usr/bin/ruby1.8-->

<!--  rvm appache2
LoadModule passenger_module /home/swathi/.rvm/gems/ruby-1.9.2-p320@stores/gems/passenger-3.0.19/ext/apache2/mod_passenger.so
PassengerRoot /home/swathi/.rvm/gems/ruby-1.9.2-p320@stores/gems/passenger-3.0.19
PassengerRuby /home/swathi/.rvm/wrappers/ruby-1.9.2-p320@stores/ruby
<VirtualHost *:80>
      ServerName www.yourhost.com
      # !!! Be sure to point DocumentRoot to 'public'!
      DocumentRoot /somewhere/public
      <Directory /somewhere/public>
         # This relaxes Apache security settings.
         AllowOverride all
         # MultiViews must be turned off.
         Options -MultiViews
      </Directory>
   </VirtualHost>
-->



<head>
  <title>Store</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
   .row-fluid .span2{background:#BBD8E9;min-height:90%;}
   .row-fluid .span10{background:#FAFAFA;height:auto;width:65%;min-height:500px; }
     .brand b{font-size:35px;}
    .navbar .nav {float: right;}
    #list_left{font-size:10px;}
    #item_name{height:30px;}
    .block1, .block2 {min-height:50%;height:auto;}
    .block1 .title, .block2 .title {height:auto;}
  </style>
</head>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="<%=root_url%>"><b>Aloo.com</b></a>
        <div class="nav-collapse">
          <ul class="nav">
            <% if user_signed_in? %>
            <li><a href=""> Logged in as <%= current_user.email %></a></li>
               <%if current_user.customer?%>
            <li><%=link_to 'My Dashboard',customer_listing_path%></li>
               <%elsif current_user.vendor?%>
            <li><%=link_to 'My Dashboard',vendor_index_path%></li>
               <%end%>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, :method=>:delete %></li>
            <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
             bvnvbnvbnvbn
                <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<div class="container-fluid">
    <div class="row-fluid">

    <div class="span2" style="width:17.53%;">
   <div class="block1">
   	<div class="title">Near by Stores</div>
        <div id="list_left"></div>
     <div id="category_block"><%= render 'home/category_levels'%></div>
   </div>
  
    </div>
    <div class="span10">
    <ul class="breadcrumb">
 <%=form_tag home_show_stores_path, :remote=>true do%>
         <%= select_tag "location_id", options_from_collection_for_select(@locations, "id", "location_name"),:prompt=>'select'%>
         <%= select_tag "radius_id",options_for_select(@radius.collect{|u| u}),:prompt=>'select' %>
         <%=text_field_tag :item_name%> <%=submit_tag "Go"%><%end%>
    </ul>
    <%= yield %>
      <%= yield :scripts%>
    </div>

      <div class="span2" style="width:10.53%;">
    	<div class="right_bar">
    		<div class="title">
    			Selected List
    		</div>
    	</div>

    </div>
    </div>
    </div>